from preprocessing import import_items, item_preprocessing
from search_engine import build_inverted_index, search_engine

'''
Main of the application
'''

# Read and import the Amazon items data from tsv file generated by the data scraping script
data = import_items('items_data.tsv')

# Preprocess the items description text
data['preprocessed_descr'] = data['description'].apply(item_preprocessing)

# Build the inverted index and save it in a csv file
inverted_index = build_inverted_index(data)
inverted_index.to_csv('inverted_index.csv')
print(inverted_index)

# Set the query string
QUERY_STRING = 'intel i5'

# Print the results order by cosine similarity
print('Results order by cosine similarity:')
print(search_engine(QUERY_STRING, inverted_index, data))